### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by MajesticSoftware** [UMBCvision/Contextual-Adversarial-Patches#1]
The link to https://github.com/marvis/pytorch-yolo2 no longer works.

**Comment by akshayv1** [comment]
Thanks for notifying. Please check the updated instructions.

**Comment by ruixin-han** [comment]
How many epochs do you need to train to run the defense program? I trained 500,000 epochs, and the ap value on the clean sample was less than 1%, and the ap value on the adversarial sample was less than 40%.
